"""Configurable keyword and phrase rules for rule-based routing.

Each rule is a tuple of lowercase tokens. A rule matches when its tokens
appear as a contiguous sequence in the tokenized prompt. This is the single
place to add or adjust rules; supervised classification replaces or
complements this layer from Milestone 2 onward.
"""

SIGNAL_RULES: dict[str, tuple[tuple[str, ...], ...]] = {
    "coding": (
        ("python",),
        ("java",),
        ("javascript",),
        ("typescript",),
        ("golang",),
        ("rust",),
        ("c++",),
        ("c#",),
        ("sql",),
        ("docker",),
        ("kubernetes",),
        ("spring", "boot"),
        ("rest", "api"),
        ("restful",),
        ("function",),
        ("class",),
        ("compiler",),
        ("debug",),
        ("refactor",),
        ("backend",),
        ("frontend",),
        ("database",),
        ("api",),
        ("algorithm",),
        ("binary", "search"),
    ),
    "math": (
        ("calculate",),
        ("computation",),
        ("multiply",),
        ("multiplied",),
        ("times",),
        ("divide",),
        ("divided",),
        ("division",),
        ("plus",),
        ("minus",),
        ("subtract",),
        ("sum",),
        ("equation",),
        ("algebra",),
        ("geometry",),
        ("calculus",),
        ("percentage",),
        ("percent",),
        ("arithmetic",),
        ("integral",),
        ("derivative",),
        ("solve",),
        ("square", "root"),
    ),
    "translation": (
        ("translate",),
        ("translation",),
        ("translator",),
        ("tamil",),
        ("telugu",),
        ("hindi",),
        ("spanish",),
        ("french",),
        ("german",),
        ("japanese",),
        ("chinese",),
        ("korean",),
    ),
    "summarization": (
        ("summarize",),
        ("summary",),
        ("summarization",),
        ("tl;dr",),
        ("condense",),
    ),
    "creative_writing": (
        ("poem",),
        ("poetry",),
        ("story",),
        ("essay",),
        ("haiku",),
        ("song",),
        ("lyrics",),
        ("fiction",),
        ("novel",),
        ("screenplay",),
    ),
    "general_qa": (
        ("what", "is"),
        ("what", "are"),
        ("why",),
        ("how",),
        ("who",),
        ("when",),
        ("where",),
        ("explain",),
    ),
}
